apiVersion: v1
kind: Secret
metadata:
  name: spring-music-db
stringData:
  spring.datasource.url: jdbc:mysql://music-mysql.mysql.svc.cluster.local/music
  spring.datasource.username: testuser
  spring.datasource.password: secret
